import { createServer } from "node:http";
import { readFileSync, existsSync } from "node:fs";
import { extname, join, resolve } from "node:path";
import { all, db, json as parseJson, one, run, transaction } from "./db.mjs";
import { createStripeCheckout, dispatchReminder, hashPassword, hashSession, id, iso, token, verifyPassword, verifyStripeSignature } from "./services.mjs";

if (existsSync(".env")) for (const line of readFileSync(".env", "utf8").split(/\r?\n/)) { const match = line.match(/^([A-Z0-9_]+)=(.*)$/); if (match && !process.env[match[1]]) process.env[match[1]] = match[2]; }
const PORT = Number(process.env.PORT || 3000); const PUBLIC = resolve("public");
const authAttempts = new Map();
const APPOINTMENT_TEMPLATE = "Bonjour {{prenom}}, merci de confirmer votre rendez-vous du {{date}} à {{heure}} avec {{entreprise}} : {{lien}}";
const INVOICE_TEMPLATE = "Bonjour {{prenom}}, la facture {{reference}} de {{montant}} est arrivée à échéance. Merci de régulariser votre paiement. — {{entreprise}}";

function reply(res, status, data, headers = {}) { const body = typeof data === "string" ? data : JSON.stringify(data); res.writeHead(status, { "Content-Type": typeof data === "string" ? "text/plain; charset=utf-8" : "application/json; charset=utf-8", "Cache-Control": "no-store", ...headers }); res.end(body); }
async function body(req, raw = false) { const chunks = []; for await (const chunk of req) chunks.push(chunk); const value = Buffer.concat(chunks).toString("utf8"); return raw ? value : value ? JSON.parse(value) : {}; }
function cookies(req) { return Object.fromEntries((req.headers.cookie || "").split(";").filter(Boolean).map((part) => { const [k, ...v] = part.trim().split("="); return [k, decodeURIComponent(v.join("="))]; })); }
function session(req) { const raw = cookies(req).cf_session; if (!raw) return null; return one(`SELECT s.id session_id,u.*,o.name organization_name,o.plan_status,o.trial_ends_at FROM sessions s JOIN users u ON u.id=s.user_id JOIN organizations o ON o.id=u.organization_id WHERE s.id=? AND s.expires_at>?`, [hashSession(raw), iso()]); }
function requireUser(req, res) { const user = session(req); if (!user) { reply(res, 401, { error: "Non authentifié" }); return null; } return user; }
function audit(user, action, entityType, entityId, payload = {}) { run("INSERT INTO audit_logs(id,organization_id,user_id,action,entity_type,entity_id,payload) VALUES(?,?,?,?,?,?,?)", [id(), user.organization_id, user.id, action, entityType, entityId, JSON.stringify(payload)]); }
function clientRow(row) { return row ? { ...row, custom_data: parseJson(row.custom_data), email_opt_in: !!row.email_opt_in, sms_opt_in: !!row.sms_opt_in } : row; }
function publicUrl(path) { return `${process.env.APP_URL || `http://localhost:${PORT}`}${path}`; }
function authAllowed(req) { const key = req.headers["x-forwarded-for"]?.split(",")[0]?.trim() || req.socket.remoteAddress || "unknown"; const now = Date.now(); const recent = (authAttempts.get(key) || []).filter((time) => now - time < 15 * 60_000); recent.push(now); authAttempts.set(key, recent); return recent.length <= 20; }

async function api(req, res, url) {
  if (req.method === "POST" && url.pathname === "/api/auth/register") {
    if (!authAllowed(req)) return reply(res, 429, { error: "Trop de tentatives. Réessayez dans quelques minutes." });
    const input = await body(req); if (!input.email || !input.password || !input.name || !input.businessName) return reply(res, 400, { error: "Tous les champs sont obligatoires" }); if (String(input.password).length < 10) return reply(res, 400, { error: "Le mot de passe doit contenir au moins 10 caractères" });
    const email = String(input.email).toLowerCase().trim(); if (one("SELECT id FROM users WHERE email=?", [email])) return reply(res, 409, { error: "Cette adresse est déjà utilisée" });
    const orgId = id(), userId = id(), rawSession = token(), trial = new Date(Date.now() + 14 * 86400000).toISOString();
    transaction(() => { run("INSERT INTO organizations(id,name,slug,trial_ends_at) VALUES(?,?,?,?)", [orgId, input.businessName, `${String(input.businessName).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}-${orgId.slice(0, 6)}`, trial]); run("INSERT INTO users(id,organization_id,email,name,password_hash) VALUES(?,?,?,?,?)", [userId, orgId, email, input.name, hashPassword(input.password)]); run("INSERT INTO settings(organization_id,business_name,appointment_message,invoice_message) VALUES(?,?,?,?)", [orgId, input.businessName, APPOINTMENT_TEMPLATE, INVOICE_TEMPLATE]); run("INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,?)", [hashSession(rawSession), userId, new Date(Date.now() + 30 * 86400000).toISOString()]); });
    return reply(res, 201, { ok: true }, { "Set-Cookie": `cf_session=${rawSession}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000${process.env.COOKIE_SECURE === "true" ? "; Secure" : ""}` });
  }
  if (req.method === "POST" && url.pathname === "/api/auth/login") { const input = await body(req); const user = one("SELECT * FROM users WHERE email=?", [String(input.email || "").toLowerCase().trim()]); if (!user || !verifyPassword(String(input.password || ""), user.password_hash)) return reply(res, 401, { error: "Identifiants incorrects" }); const raw = token(); run("INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,?)", [hashSession(raw), user.id, new Date(Date.now() + 30 * 86400000).toISOString()]); return reply(res, 200, { ok: true }, { "Set-Cookie": `cf_session=${raw}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000${process.env.COOKIE_SECURE === "true" ? "; Secure" : ""}` }); }
  if (req.method === "POST" && url.pathname === "/api/auth/logout") { const raw = cookies(req).cf_session; if (raw) run("DELETE FROM sessions WHERE id=?", [hashSession(raw)]); return reply(res, 200, { ok: true }, { "Set-Cookie": "cf_session=; Path=/; HttpOnly; Max-Age=0" }); }
  if (req.method === "GET" && url.pathname === "/api/me") { const user = session(req); return reply(res, 200, user ? { user: { id: user.id, name: user.name, email: user.email, role: user.role }, organization: { id: user.organization_id, name: user.organization_name, planStatus: user.plan_status, trialEndsAt: user.trial_ends_at } } : { user: null }); }

  if (req.method === "GET" && url.pathname.startsWith("/confirm/")) { const [appointmentToken, action] = url.pathname.split("/").slice(2); const appointment = one("SELECT * FROM appointments WHERE confirmation_token=?", [appointmentToken]); if (!appointment || !["yes", "no"].includes(action)) return reply(res, 404, "Lien invalide ou expiré"); run(action === "yes" ? "UPDATE appointments SET status='confirmed',confirmed_at=? WHERE id=?" : "UPDATE appointments SET status='cancelled',cancelled_at=? WHERE id=?", [iso(), appointment.id]); return reply(res, 200, action === "yes" ? "Votre rendez-vous est confirmé. Merci !" : "Votre rendez-vous est annulé. Merci de contacter le professionnel si nécessaire."); }
  if (req.method === "POST" && url.pathname === "/api/cron/reminders") { if (req.headers.authorization !== `Bearer ${process.env.CRON_SECRET}`) return reply(res, 401, { error: "Accès refusé" }); const result = await processReminders(); return reply(res, 200, result); }
  if (req.method === "POST" && url.pathname === "/api/stripe/webhook") { const raw = await body(req, true); if (!verifyStripeSignature(raw, req.headers["stripe-signature"])) return reply(res, 400, { error: "Signature invalide" }); const event = JSON.parse(raw); handleStripeEvent(event); return reply(res, 200, { received: true }); }

  const user = requireUser(req, res); if (!user) return;
  if (req.method === "GET" && url.pathname === "/api/dashboard") { const org = user.organization_id; return reply(res, 200, { counts: { clients: one("SELECT COUNT(*) value FROM clients WHERE organization_id=?", [org]).value, upcoming: one("SELECT COUNT(*) value FROM appointments WHERE organization_id=? AND status IN ('scheduled','confirmed') AND starts_at>=?", [org, iso()]).value, unpaid: one("SELECT COUNT(*) value FROM invoices WHERE organization_id=? AND status='pending'", [org]).value }, clients: all("SELECT * FROM clients WHERE organization_id=? ORDER BY updated_at DESC LIMIT 6", [org]).map(clientRow), appointments: all(`SELECT a.*,c.first_name,c.last_name FROM appointments a JOIN clients c ON c.id=a.client_id WHERE a.organization_id=? AND a.starts_at>=? ORDER BY a.starts_at LIMIT 6`, [org, iso()]), invoices: all(`SELECT i.*,c.first_name,c.last_name FROM invoices i JOIN clients c ON c.id=i.client_id WHERE i.organization_id=? ORDER BY i.created_at DESC LIMIT 6`, [org]) }); }
  if (req.method === "GET" && url.pathname === "/api/clients") { const q = `%${url.searchParams.get("q") || ""}%`; return reply(res, 200, { clients: all("SELECT * FROM clients WHERE organization_id=? AND (first_name||' '||last_name LIKE ? OR company LIKE ? OR email LIKE ?) ORDER BY last_name,first_name", [user.organization_id, q, q, q]).map(clientRow), fields: all("SELECT * FROM custom_fields WHERE organization_id=? ORDER BY position,created_at", [user.organization_id]) }); }
  if (req.method === "POST" && url.pathname === "/api/clients") { const input = await body(req); if (!input.firstName || !input.lastName) return reply(res, 400, { error: "Prénom et nom obligatoires" }); const clientId = id(); run(`INSERT INTO clients(id,organization_id,first_name,last_name,company,email,phone,address,notes,status,email_opt_in,sms_opt_in,custom_data) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`, [clientId,user.organization_id,input.firstName,input.lastName,input.company||"",input.email||"",input.phone||"",input.address||"",input.notes||"",input.status||"active",input.emailOptIn===false?0:1,input.smsOptIn===false?0:1,JSON.stringify(input.customData||{})]); audit(user,"create","client",clientId); return reply(res,201,{ client: clientRow(one("SELECT * FROM clients WHERE id=?",[clientId])) }); }
  if (req.method === "PUT" && /^\/api\/clients\/[^/]+$/.test(url.pathname)) { const clientId=url.pathname.split("/").pop(), input=await body(req); const existing=one("SELECT id FROM clients WHERE id=? AND organization_id=?",[clientId,user.organization_id]); if(!existing)return reply(res,404,{error:"Client introuvable"}); run(`UPDATE clients SET first_name=?,last_name=?,company=?,email=?,phone=?,address=?,notes=?,status=?,email_opt_in=?,sms_opt_in=?,custom_data=?,updated_at=? WHERE id=?`,[input.firstName,input.lastName,input.company||"",input.email||"",input.phone||"",input.address||"",input.notes||"",input.status||"active",input.emailOptIn===false?0:1,input.smsOptIn===false?0:1,JSON.stringify(input.customData||{}),iso(),clientId]); audit(user,"update","client",clientId); return reply(res,200,{ok:true}); }
  if (req.method === "DELETE" && /^\/api\/clients\/[^/]+$/.test(url.pathname)) { const clientId=url.pathname.split("/").pop(); run("DELETE FROM clients WHERE id=? AND organization_id=?",[clientId,user.organization_id]); audit(user,"delete","client",clientId); return reply(res,200,{ok:true}); }
  if (req.method === "POST" && url.pathname === "/api/custom-fields") { const input=await body(req); if(!input.label)return reply(res,400,{error:"Libellé obligatoire"}); const fieldId=id(); run("INSERT INTO custom_fields(id,organization_id,label,field_type,required,position) VALUES(?,?,?,?,?,?)",[fieldId,user.organization_id,input.label,input.fieldType||"text",input.required?1:0,Number(input.position||0)]); return reply(res,201,{id:fieldId}); }
  if (req.method === "DELETE" && /^\/api\/custom-fields\/[^/]+$/.test(url.pathname)) { run("DELETE FROM custom_fields WHERE id=? AND organization_id=?",[url.pathname.split("/").pop(),user.organization_id]); return reply(res,200,{ok:true}); }
  if (req.method === "GET" && url.pathname === "/api/appointments") return reply(res,200,{appointments:all(`SELECT a.*,c.first_name,c.last_name,c.email,c.phone FROM appointments a JOIN clients c ON c.id=a.client_id WHERE a.organization_id=? ORDER BY a.starts_at DESC`,[user.organization_id])});
  if (req.method === "POST" && url.pathname === "/api/appointments") { const input=await body(req); if(!input.clientId||!input.title||!input.startsAt)return reply(res,400,{error:"Client, objet et date obligatoires"}); const appointmentId=id(); run("INSERT INTO appointments(id,organization_id,client_id,title,starts_at,ends_at,location,notes,confirmation_token) VALUES(?,?,?,?,?,?,?,?,?)",[appointmentId,user.organization_id,input.clientId,input.title,input.startsAt,input.endsAt||null,input.location||"",input.notes||"",token()]); audit(user,"create","appointment",appointmentId); return reply(res,201,{id:appointmentId}); }
  if (req.method === "GET" && url.pathname === "/api/invoices") return reply(res,200,{invoices:all(`SELECT i.*,c.first_name,c.last_name FROM invoices i JOIN clients c ON c.id=i.client_id WHERE i.organization_id=? ORDER BY i.created_at DESC`,[user.organization_id])});
  if (req.method === "POST" && url.pathname === "/api/invoices") { const input=await body(req); if(!input.clientId||!input.reference||!input.amount||!input.dueDate)return reply(res,400,{error:"Informations incomplètes"}); const invoiceId=id(); run("INSERT INTO invoices(id,organization_id,client_id,reference,amount_cents,due_date) VALUES(?,?,?,?,?,?)",[invoiceId,user.organization_id,input.clientId,input.reference,Math.round(Number(input.amount)*100),input.dueDate]); audit(user,"create","invoice",invoiceId); return reply(res,201,{id:invoiceId}); }
  if (req.method === "POST" && /^\/api\/invoices\/[^/]+\/paid$/.test(url.pathname)) { const invoiceId=url.pathname.split("/")[3]; run("UPDATE invoices SET status='paid',paid_at=? WHERE id=? AND organization_id=?",[iso(),invoiceId,user.organization_id]); return reply(res,200,{ok:true}); }
  if (req.method === "GET" && url.pathname === "/api/settings") return reply(res,200,{settings:one("SELECT * FROM settings WHERE organization_id=?",[user.organization_id]),fields:all("SELECT * FROM custom_fields WHERE organization_id=? ORDER BY position",[user.organization_id])});
  if (req.method === "PUT" && url.pathname === "/api/settings") { const input=await body(req); run(`UPDATE settings SET business_name=?,brand_color=?,logo_url=?,timezone=?,reminder_hours=?,invoice_reminder_days=?,email_enabled=?,sms_enabled=?,appointment_message=?,invoice_message=?,updated_at=? WHERE organization_id=?`,[input.businessName,input.brandColor,input.logoUrl||"",input.timezone||"Europe/Paris",Number(input.reminderHours||48),Number(input.invoiceReminderDays||3),input.emailEnabled?1:0,input.smsEnabled?1:0,input.appointmentMessage,input.invoiceMessage,iso(),user.organization_id]); run("UPDATE organizations SET name=? WHERE id=?",[input.businessName,user.organization_id]); audit(user,"update","settings",user.organization_id); return reply(res,200,{ok:true}); }
  if (req.method === "GET" && url.pathname === "/api/export") { const data={exportedAt:iso(),clients:all("SELECT * FROM clients WHERE organization_id=?",[user.organization_id]),appointments:all("SELECT * FROM appointments WHERE organization_id=?",[user.organization_id]),invoices:all("SELECT * FROM invoices WHERE organization_id=?",[user.organization_id])}; return reply(res,200,data,{"Content-Disposition":"attachment; filename=clientflow-export.json"}); }
  if (req.method === "POST" && url.pathname === "/api/billing/checkout") { const org=one("SELECT * FROM organizations WHERE id=?",[user.organization_id]); const checkout=await createStripeCheckout({organization:org,userEmail:user.email}); return reply(res,200,{url:checkout.url}); }
  return reply(res,404,{error:"Route introuvable"});
}

async function processReminders() {
  const now=new Date(), sent=[];
  const appointments=all(`SELECT a.*,c.first_name,c.last_name,c.email,c.phone,c.email_opt_in,c.sms_opt_in,s.* FROM appointments a JOIN clients c ON c.id=a.client_id JOIN settings s ON s.organization_id=a.organization_id WHERE a.status='scheduled' AND a.reminder_sent_at IS NULL AND a.starts_at>?`,[iso(now)]).filter((a)=>new Date(a.starts_at).getTime()-now.getTime()<=a.reminder_hours*3600000);
  for(const item of appointments){const start=new Date(item.starts_at),link=`${publicUrl(`/confirm/${item.confirmation_token}/yes`)} (annuler : ${publicUrl(`/confirm/${item.confirmation_token}/no`)})`;try{const results=await dispatchReminder({client:item,settings:item,kind:"appointment",data:{date:start.toLocaleDateString("fr-FR"),heure:start.toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"}),lien:link}});for(const message of results)run("INSERT INTO message_logs(id,organization_id,client_id,channel,kind,destination,status,provider_id) VALUES(?,?,?,?,?,?,?,?)",[id(),item.organization_id,item.client_id,message.channel,"appointment",message.destination,message.result.skipped?"skipped":"sent",message.result.id||null]);run("UPDATE appointments SET reminder_sent_at=? WHERE id=?",[iso(),item.id]);sent.push(item.id);}catch(error){run("INSERT INTO message_logs(id,organization_id,client_id,channel,kind,destination,status,error) VALUES(?,?,?,?,?,?,?,?)",[id(),item.organization_id,item.client_id,"mixed","appointment",item.email||item.phone,"failed",String(error.message)]);}}
  const invoices=all(`SELECT i.*,c.first_name,c.last_name,c.email,c.phone,c.email_opt_in,c.sms_opt_in,s.* FROM invoices i JOIN clients c ON c.id=i.client_id JOIN settings s ON s.organization_id=i.organization_id WHERE i.status='pending' AND date(i.due_date)<=date('now') AND (i.reminder_sent_at IS NULL OR datetime(i.reminder_sent_at)<=datetime('now','-'||s.invoice_reminder_days||' days'))`);
  for(const item of invoices){try{const results=await dispatchReminder({client:item,settings:item,kind:"invoice",data:{reference:item.reference,montant:new Intl.NumberFormat("fr-FR",{style:"currency",currency:item.currency}).format(item.amount_cents/100)}});for(const message of results)run("INSERT INTO message_logs(id,organization_id,client_id,channel,kind,destination,status,provider_id) VALUES(?,?,?,?,?,?,?,?)",[id(),item.organization_id,item.client_id,message.channel,"invoice",message.destination,message.result.skipped?"skipped":"sent",message.result.id||null]);run("UPDATE invoices SET reminder_sent_at=? WHERE id=?",[iso(),item.id]);sent.push(item.id);}catch(error){run("INSERT INTO message_logs(id,organization_id,client_id,channel,kind,destination,status,error) VALUES(?,?,?,?,?,?,?,?)",[id(),item.organization_id,item.client_id,"mixed","invoice",item.email||item.phone,"failed",String(error.message)]);}}
  return {processed:appointments.length+invoices.length,sent};
}
function handleStripeEvent(event){const object=event.data?.object||{},orgId=object.client_reference_id||object.metadata?.organization_id;if(!orgId)return;if(event.type==="checkout.session.completed")run("UPDATE organizations SET plan_status='active',stripe_customer_id=?,stripe_subscription_id=? WHERE id=?",[object.customer||null,object.subscription||null,orgId]);if(["customer.subscription.deleted","invoice.payment_failed"].includes(event.type))run("UPDATE organizations SET plan_status=? WHERE stripe_subscription_id=?",[event.type==="customer.subscription.deleted"?"cancelled":"past_due",object.subscription||object.id]);if(event.type==="invoice.paid")run("UPDATE organizations SET plan_status='active' WHERE stripe_customer_id=?",[object.customer]);}

const types={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json; charset=utf-8",".svg":"image/svg+xml",".webmanifest":"application/manifest+json"};
createServer(async(req,res)=>{try{const url=new URL(req.url||"/",`http://${req.headers.host||"localhost"}`);if(url.pathname.startsWith("/api/")||url.pathname.startsWith("/confirm/"))return await api(req,res,url);const relative=url.pathname==="/"?"index.html":url.pathname.slice(1);const file=join(PUBLIC,relative);if(!file.startsWith(PUBLIC)||!existsSync(file))return reply(res,404,"Introuvable");res.writeHead(200,{"Content-Type":types[extname(file)]||"application/octet-stream","Cache-Control":relative==="index.html"?"no-cache":"public, max-age=3600"});res.end(readFileSync(file));}catch(error){console.error(error);reply(res,500,{error:process.env.NODE_ENV==="production"?"Une erreur est survenue":error.message});}}).listen(PORT,()=>console.log(`ClientFlow Pro — http://localhost:${PORT}`));
